== LibVideoOut
*Init*: Sets the resolution
Roughly describing the requirements for LibVideoOut API

.LibVideoOut rough structure
[plantuml, libVideoOut-functions, png]
----
include::../uml/Class_LibVideoOut_api.puml[]
----

.LibVideoOut Sequence-Diagram
[plantuml, libVideoOut-Seq, png]
----
include::../uml/Seq_VideoOut.puml[]
----


[TIP] 
SDL Event and Flip can run concurrently. FlipQueue could run in a loop and be controled by GameMainLoop


=== VideoOutOpen()
Checks if a unused VideoOutConfig is available (1..VIDEO_OUT_NUM_MAX) and initializes it.+ 
Array Index "starts" with 1. Index is returned.

=== VideoOutGetResolutionStatus(): RetByRef VideoOutResolutionStatus of the handle

=== VideoOutAddFlipEvent(udata)
 Creates KernelEqueueEvent, adds it to the KernelEventQueue and VideoOutConfig::flip_eqs
....
Ident: VIDEO_OUT_EVENT_FLIP_Queue
Queue: KERNEL_EVFILT_VIDEO_OUT
   event.filter.data = videoOutConfig 
   event.event.udata = udata

callbacks:
   flip_event_delete_func
   flip_event_reset_func
   flip_event_trigger_func
....

=== VideoOutSetBufferAttribute()
 Only wants the VideoOutBufferAttribute. Which is filled only with the information provided as values.
-> No Internal changes

=== VideoOutRegisterBuffers()
[small]
----
start_index = 0
buffer_num = 2
pixel_format   = 0x80000000
tiling_mode    = 0
aspect_ratio   = 0
width          = 1920
height         = 1080
pitch_in_pixel = 1920
option = 0
----

Calls Graphics::WindowWaitForGraphicInitialized()  and Graphics::GraphicsRenderCreateContext().

----
for start_index < buffer_num
    Graphics::GpuMemoryCreateObject()
----

[NOTE] 
Creates the VideoOutBuffers at the provided *addresses (Sysstem Memory)* and stores them in VideoOutConfig::buffers. +
buffer := System Memory Address, buffer_vulkan := GpuMemoryCreateObject


=== VideoOutSubmitFlip()
g_video_out_context->GetFlipQueue().Submit(ctx, index, flip_arg)

-> Draws the vulkan_buffer to videoOut and increments the frame counter.