@startuml
class LibGraphics{
    GraphicsSetVsShader()
    GraphicsUpdateVsShader()
    GraphicsSetPsShader()
    GraphicsSetPsShader350()
    GraphicsUpdatePsShader()
    GraphicsUpdatePsShader350()
    GraphicsSetCsShaderWithModifier()
    GraphicsDrawIndex()
    GraphicsDrawIndexAuto()
    GraphicsSubmitCommandBuffers()
    GraphicsSubmitAndFlipCommandBuffers()
    GraphicsSubmitDone()
    GraphicsAreSubmitsAllowed()
    GraphicsFlushMemory()
    GraphicsAddEqEvent()
    GraphicsDeleteEqEvent()
    GraphicsDrawInitDefaultHardwareState()
    GraphicsDrawInitDefaultHardwareState175()
    GraphicsDrawInitDefaultHardwareState200()
    GraphicsDrawInitDefaultHardwareState350()
    GraphicsDispatchInitDefaultHardwareState()
    GraphicsInsertWaitFlipDone()
    GraphicsDispatchDirect()
    GraphicsMapComputeQueue()
    GraphicsUnmapComputeQueue()
    GraphicsComputeWaitOnAddress()
    GraphicsDingDong()
    GraphicsInsertPushMarker()
    GraphicsInsertPopMarker()
    GraphicsSetEmbeddedVsShader()
    GraphicsRegisterOwner()
    GraphicsRegisterResource()
    GraphicsGetGpuCoreClockFrequency()
    GraphicsIsUserPaEnabled()
    GraphicsGetTheTessellationFactorRingBufferBaseAddress()
}
@enduml